# Generated by Django 4.1.3 on 2022-11-30 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('applicant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('condition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('post', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('vacancy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('salary', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birja.company')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='birja.post')),
            ],
        ),
        migrations.CreateModel(
            name='ListPost',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('applicant_id', models.IntegerField()),
            ],
            options={
                'unique_together': {('post_id', 'applicant_id')},
            },
        ),
    ]
