# Generated by Django 4.1.4 on 2022-12-28 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birja', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='applicant_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='vacancy_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birja.post'),
        ),
    ]
